/*
 * Copyright 2021-2023 NoSugarIce
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

DROP TABLE film_review IF EXISTS;
CREATE TABLE film_review
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_name  VARCHAR(100) NOT NULL,
    sex        VARCHAR(1)   NOT NULL,
    movie_name VARCHAR(100) NOT NULL,
    score      INTEGER      NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO film_review VALUES (0, 'A', '男', '阿甘正传', 8);
INSERT INTO film_review VALUES (1, 'B', '女', '星际穿越', 9);
INSERT INTO film_review VALUES (2, 'C', '女', '大话西游之大圣娶亲', 8);
INSERT INTO film_review VALUES (3, 'D', '男', '这个杀手不太冷', 7);
INSERT INTO film_review VALUES (4, 'E', '女', '疯狂动物城', 8);
INSERT INTO film_review VALUES (5, 'F', '男', '罗马假日', 9);
INSERT INTO film_review VALUES (6, 'G', '女', '阿甘正传', 9);
INSERT INTO film_review VALUES (7, 'H', '男', '疯狂动物城', 8);
INSERT INTO film_review VALUES (8, 'I', '女', '阿甘正传', 9);
INSERT INTO film_review VALUES (9, 'J', '男', '大话西游之月光宝盒', 9);
