DROP TABLE "DEMO"."STUDENT";
CREATE TABLE "DEMO"."STUDENT"
(
    "ID"           VARCHAR2(32) NOT NULL ENABLE,
    "NAME"         VARCHAR2(20) NOT NULL ENABLE,
    "AGE"          NUMBER(*, 0) NOT NULL ENABLE,
    "SEX"          NUMBER(*, 0) NOT NULL ENABLE,
    "SNO"          VARCHAR2(20) NOT NULL ENABLE,
    "PHONE"        VARCHAR2(20)  DEFAULT NULL,
    "ADDRESS"      VARCHAR2(100) DEFAULT NULL,
    "CARD_BALANCE" NUMBER(6, 2)  DEFAULT NULL,
    "STATUS"       NUMBER(*, 0) NOT NULL ENABLE,
    "VERSION"      NUMBER(*, 0) NOT NULL ENABLE,
    "CREATED_AT"   DATE         NOT NULL ENABLE,
    "UPDATED_AT"   DATE          DEFAULT NULL,
    "DISABLED_AT"  DATE          DEFAULT NULL,
    PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING TABLESPACE "USERS" ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";
